variables:
  RELEASE_BRANCH: 'release-0.7'
  PROJECT_SSH: "git@github.lan:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
  REMOTE_SSH:  "git@github.com:mambaru/${CI_PROJECT_NAME}.git"

stages:
  - build
  - check
  - clean
  - release
  - publish

base-build:
  stage: build
  script:
    - ./.ci/build-and-test.sh g++ 98 Release
    - ./.ci/build-and-test.sh g++ 11 Release
  except:
    - /^draft.*$/

full-build:
  stage: build
  script:
    - ./.ci/build-and-test.sh clang++ 98 Release
    - ./.ci/build-and-test.sh clang++ 11 Release
    - ./.ci/build-and-test.sh g++ 14 Release
    - ./.ci/build-and-test.sh clang++ 14 Release
    - ./.ci/build-and-test.sh g++ 98 Debug
    - ./.ci/build-and-test.sh g++ 11 Debug
    - ./.ci/build-and-test.sh g++ 14 Debug
    - ./.ci/build-and-test.sh clang++ 98 Debug
    - ./.ci/build-and-test.sh clang++ 11 Debug
    - ./.ci/build-and-test.sh clang++ 14 Debug
  only:
    - master
    - tags
    - /^build.*$/
  
cppcheck:
  stage: check
  script:
    - ./.ci/cppcheck.sh --std=c++03
    - ./.ci/cppcheck.sh --std=c++11
    - ./.ci/cppcheck.sh --std=c++14
  only:
    - master
    - tags
    - /^check.*$/

release-branch:
  stage: release
  script:
    - echo git push -f ${PROJECT_SSH} ${CI_COMMIT_REF_NAME}:refs/heads/${RELEASE_BRANCH}
    - git push -f ${PROJECT_SSH} ${CI_COMMIT_REF_NAME}:refs/heads/${RELEASE_BRANCH}
  only:
    - tags

make-merge-request:
  stage: release
  script:
    - if [ "${RELEASE_BRANCH}" != "${CI_COMMIT_REF_NAME}" ]; then exit 1; fi
#    - ./.ci/headtag.sh ${CI_COMMIT_REF_NAME}
    - HOST=${CI_PROJECT_URL}  CI_PROJECT_ID=${CI_PROJECT_ID} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} ./.ci/automr.sh
  only:
    - /^release.*$/

delete-branches:
  stage: clean
  script:
    - git push ${PROJECT_SSH} :${CI_COMMIT_REF_NAME}
  only:
    - /^build.*$/
    - /^check.*$/

faslib-push:
  stage: publish
  only:
    - master
  script:
    - git push -f ${REMOTE_SSH} master:mambaru
    - git push -f --tags ${REMOTE_SSH} master:mambaru
