dist:     trusty
sudo:     required

language: cpp

os:
  - linux

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libc++-dev libboost-dev
  - sudo apt-get install -y libboost-system-dev libboost-program-options-dev
  - sudo apt-get install -y libboost-filesystem-dev libboost-date-time-dev libboost-regex-dev valgrind doxygen

compiler:
  - g++
  - clang++

branches:
  only:
    - mambaru
    - master

script:
  - git submodule sync
  - git submodule update --init --force
  - mkdir -p build
  - pushd build
  -   cmake .. -DCMAKE_CXX_COMPILER=$TRAVIS_COMPILER -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DPARANOID_WARNINGS=ON
  -   cmake --build .
  -   ctest --output-on-failure
  -   make clean
  - popd
