name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo locale-gen ru_RU
        sudo locale-gen ru_RU.UTF-8
        sudo update-locale
        sudo apt-get install -y libboost-system-dev libboost-program-options-dev
        sudo apt-get install -y libboost-filesystem-dev libboost-date-time-dev libboost-regex-dev
        sudo apt-get install -y doxygen lcov
    - name: init
      run: |
        mkdir -p build
        git submodule update --init external/cmake-ci
        pushd external/cmake-ci
          git checkout master
        popd
        rsync -arv external/cmake-ci/root-ci/ ./
    - name: make doc
      run: make doc
    - name: make, test and coverage report
      run: |
        make coverage-report
        pushd build
          export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
          bash <(curl -s https://codecov.io/bash)
        popd
    - name: make gh-pages
      run: |
        git clone -b gh-pages https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git /tmp/gh-pages
        docdir="$PWD/docs/html/"
        pushd /tmp/gh-pages
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          rsync -a --update $docdir ./
          git add --all
          COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
          git commit -m "${COMMIT_MESSAGE}"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages:gh-pages
        popd
        date +"%F %X" >> ./.github/build_history.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: mambaru
        branch-suffix: none
